/* Ajuda de cada controle — mostrada no balao do canto superior direito.
   Formato: id -> { t:titulo, b:o que faz, img:efeito na imagem, hw:custo de hardware, hint }
   Aqui moram as explicacoes que antes poluiam a UI ("roda na CPU", "muda pouco"...),
   reescritas em linguagem de usuario. */
window.HELP = {
  _default: { t:"GSMDE Studio", b:"Passe o mouse sobre qualquer controle para ver aqui o que ele faz, o efeito na imagem e o custo de hardware.", },

  pos:{ t:"Prompt positivo", b:"Descreve a imagem. O roteador le este texto e ativa sozinho os especialistas cujas palavras aparecem (ex.: 'cafe', 'rio', 'orelhas de gato').",
    img:"Define assunto, cena e estilo.", hw:"O codificador de texto roda 100% na CPU — nao pesa na GPU." },
  neg:{ t:"Prompt negativo", b:"O que voce NAO quer na imagem (baixa qualidade, extra de dedos, marca d'agua...).",
    img:"Empurra a geracao para longe destes termos.", hw:"Sem custo extra." },

  auto:{ t:"Roteamento automatico", b:"Le o prompt e escolhe os especialistas sozinho — voce nao precisa saber os nomes dos centros. Desligue so para escolher na mao.",
    img:"Cada especialista pinta a regiao dele.", hw:"So texto/CPU; nao afeta a GPU." },
  maxCentros:{ t:"Maximo de centros", b:"Teto de especialistas ativos ao mesmo tempo, ordenados pela forca do casamento com o prompt.",
    img:"Mais centros = mais conceitos atendidos.", hw:"Cada centro ~0,7GB paginado por passo (RAM↔VRAM). Mais centros = mais lento e mais RAM.",
    hint:"6 e um bom equilibrio em 8GB." },
  verCentros:{ t:"Ver o que ele escolhe", b:"Mostra quais especialistas o roteador ativaria para o prompt atual, antes de gerar.",
    img:"—", hw:"Instantaneo (so texto)." },

  escala:{ t:"Forca dos especialistas", b:"O quanto os especialistas se sobrepoem a base. Baixo = mais base; alto = mais o estilo treinado de cada centro.",
    img:"Alto reforca o traco dos especialistas; muito alto pode 'inundar' a cena.", hw:"Sem custo extra." },
  gw:{ t:"Peso dos globais", b:"Forca dos centros SEM territorio (estilo, camera) — aplicam na tela toda em vez de uma regiao.",
    img:"Ajusta estilo/enquadramento global.", hw:"Sem custo extra." },
  backbone:{ t:"Backbone dominante", b:"Base fixa em 1.0; cada centro so reforca a propria regiao pela cobertura. Em 0 os centros substituem a base (tende a inundar).",
    img:"Alto = cena mais coesa; baixo = centros mais soltos.", hw:"Sem custo extra." },
  backboneVar:{ t:"Modelo base",
    b:"Qual UNet vai para a placa. A original tem 4,78 GB; as variantes cortam camadas transformer do nivel profundo SO' NA DESCIDA, mantendo a subida inteira — a descida codifica, a subida reconstroi detalhe, e cortar a subida destroi a imagem.",
    img:"Em cena com pessoa as reduzidas igualam ou superam a original. O que elas perdem e' detalhe de material e objeto pequeno: veio de madeira, ferramenta na bancada.",
    hw:"Medido em 54 geracoes a 1024: a ORIGINAL e' a unica que transborda para a RAM (0,30 GB contra 0,08). A d5u10 e' 27% mais rapida e usa 1 GB a menos.",
    hint:"d5u10 e' a recomendada. 'Todas' gera a mesma seed em cada modelo, para comparar — fixa a seed sozinha." },
  size:{ t:"Largura x altura", b:"Tamanho em que a imagem nasce, antes do hires/ultra. Os dois campos sao livres — qualquer proporcao (16:9, 2:7, 1:1). Valores fora do multiplo de 8 sao arredondados: o latente e' 1/8 da imagem.",
    img:"Define o enquadramento. Maior nasce com mais estrutura, mas foge da resolucao de treino se exagerar.", hw:"VRAM e tempo crescem com a AREA (largura x altura), nao com o lado. 768x768 e o ponto seguro em 8GB.",
    hint:"Prefira subir com o ganho do hires/ultra, nao com a resolucao base." },
  cor:{ t:"Cor (grading)", b:"Brilho, contraste, saturacao, sombras, highlights e nitidez aplicados por pos-processamento no FIM do pipeline — depois do ultra, sem redesenhar detalhe.",
    img:"Ajusta a luz da imagem pronta.", hw:"Custo desprezivel (numpy na CPU).",
    hint:"A ordem importa: gerar -> ultra -> cor. Grading no meio faz o color-match puxar a vibracao de volta ao neutro." },
  parar:{ t:"Parar", b:"Encerra o worker do GSMDE e solta os ~7GB de VRAM. Fica SEMPRE disponivel: o worker e' outro processo e pode estar vivo (ou travado) mesmo quando a UI acha que nao ha nada rodando — e' exatamente ai que voce precisa dele.",
    img:"—", hw:"Libera a VRAM na hora; a proxima geracao recarrega o motor (~1,5min).",
    hint:"Sem geracao em andamento nao faz mal nenhum: so responde que nao havia nada." },
  abaI2i:{ t:"i2i com mascara manual", b:"Voce sobe uma imagem, pinta a area a refazer e o modelo gera ALI do zero, guiado pelo seu prompt, encaixando no resto da imagem.",
    img:"So a area pintada muda; o resto fica pixel a pixel igual.", hw:"Processa so a regiao da mascara + halo, entao custa muito menos que refazer a imagem toda.",
    hint:"Nao e' re-noise: dentro da mascara a difusao parte de ruido puro, entao aparece informacao NOVA em vez de uma variacao do que ja estava la." },
  i2iPrompt:{ t:"Prompt do i2i", b:"Descreve so o que deve aparecer DENTRO da mascara. O entorno ja esta na imagem e chega ao modelo pelo halo.",
    img:"Define o conteudo novo.", hw:"Sem custo extra." },
  i2iPincel:{ t:"Pincel da mascara", b:"Pintado = area que sera gerada do zero. A mascara e' desenhada na resolucao NATIVA da imagem (a tela so aparece reduzida), p/ a borda nao ganhar erro de reescala.",
    img:"Define exatamente onde o novo conteudo nasce.", hw:"Quanto maior a area, maior a regiao processada." },
  i2iContextos:{ t:"Os quatro contextos", b:"O que o modelo sabe ao gerar dentro da mascara vem de quatro fontes independentes: GLOBAL (a imagem inteira, via IP-Adapter) diz o que a cena e'; VIZINHO (o halo) diz o que ha em volta; COSTURA (feather) so cuida da borda; PROMPT diz o que voce quer. Misturar bem os quatro e' o que separa um i2i coerente de um remendo.",
    img:"Global baixo = redesenha 'uma' coisa plausivel em vez DAQUELA coisa. Vizinho baixo = ignora o entorno. Costura baixa = borda dura.",
    hw:"Vizinho e costura AUMENTAM a regiao processada (e a VRAM); global custa o encoder de imagem do IP-Adapter, uma vez por geracao.",
    hint:"Nenhum deles e' re-noise: o nucleo sempre nasce de ruido puro. VER a imagem e PARTIR dela sao coisas diferentes." },
  i2iHalo:{ t:"Halo e costura", b:"Halo = anel ao redor da mascara que o modelo VE e NAO reescreve: e' dele que vem luz, perspectiva e paleta p/ o novo encaixar. Blending = a rampa de feather que costura a borda.",
    img:"Halo maior = mais contexto, encaixe melhor. Blending maior = transicao mais suave.", hw:"Os dois AUMENTAM a regiao processada e portanto a VRAM.",
    hint:"Sem tiling e sem supersampling de proposito: reescalar so a parte mascarada daria estatistica de ruido diferente da vizinhanca e a costura apareceria." },
  abaConfig:{ t:"Aba de configuracao", b:"Troca a coluna da esquerda: em vez dos prompts e ajustes DA IMAGEM, mostra os ajustes do BACKEND — onde os pesos moram, offload, execucao e caminhos. Valem p/ todas as geracoes e ficam salvos.",
    img:"Nao mexe na imagem.", hw:"Numa placa com folga (16GB+) boa parte destes ajustes deixa de ser necessaria: o automatico simplesmente mantem tudo residente.",
    hint:"Os controles sao os MESMOS da aba Gerar, so mudaram de lugar — nao ha duas copias do estado." },
  ramBuffer:{ t:"Buffer de RAM", b:"Quanto da RAM os centros podem ocupar. Eles moram na RAM e sobem para a placa um por vez, entao quem limita QUANTOS cabem e' a RAM, nao a VRAM. O valor e' seu: nao ha veto ao configurar.",
    img:"Nao muda a imagem — muda quantos centros cabem sem a maquina sofrer.",
    hw:"Tres faixas: nivel 1 quando os centros passam do buffer, nivel 2 quando passam 20% alem. Nenhuma das duas interrompe. So o teto do SISTEMA em 83% bloqueia a geracao — ali o risco e' entrar em swap, onde cada passo levaria minutos.",
    hint:"Os niveis 1 e 2 existem so' para incomodar ate a configuracao ficar sa. Se voce sabe o que esta fazendo, pode ignorar e gerar." },
  caminhos:{ t:"Pastas", b:"Onde o GSMDE procura modelos e onde grava. Vazio = automatico: ele detecta a biblioteca no padrao SD.Next (Stable-diffusion/, Lora/, VAE/, yolo/...) e deriva o resto dela. O que voce digitar ganha da deteccao.",
    img:"Nao muda a imagem — mas apontar para o lugar errado faz o motor gerar SEM os centros, sem erro nenhum, so resultado pior.",
    hw:"Disco importa na carga fria: NVMe sobe os pesos bem mais rapido que SATA.",
    hint:"De onde os pesos vem AGORA:" },
  offloadBase:{ t:"Offload do UNet base",
    b:"Onde os pesos do backbone moram durante a geracao. 'Nenhum' mantem os ~4GB residentes na placa; os demais deixam o accelerate mover submodulos entre RAM e VRAM na hora do forward.",
    img:"Nao muda a imagem — muda onde os mesmos pesos ficam.",
    hw:"MEDIDO em 16/08, 5 centros a 768, mesma cena e seed: sequential 20,4 s/passo · model 44,5 · group 50,7 · NENHUM 122,7. Sequential e' 6x mais rapido que manter residente, e ainda usa a MENOR VRAM (4,72GB contra 5,96).",
    hint:"O resultado contraria a intuicao: mover 30GB por passo pelo PCIe sai mais barato que deixar residente. Com o backbone fixo ha 6GB de despejo, e o driver pagina sob demanda no meio do calculo — trafego caotico. O accelerate faz transferencia ORDENADA. O que importa e' o padrao de acesso, nao o volume." },
  paginacao:{ t:"Paginacao dos nichos", b:"Onde os especialistas moram. Paginado = na RAM, subindo p/ a placa um por vez; residente = ficam na VRAM. AUTOMATICO le a memoria livre da placa e enche ate o orcamento, deixando uma reserva p/ as ativacoes.",
    img:"Nao muda a imagem — so o tempo e a memoria.", hw:"Paginar custa uma ida e volta pelo PCIe POR NICHO, POR PASSO: 26 passos x 5 centros = 260 transferencias. Em placa grande isso e' compute esperando barramento a toa.",
    hint:"Numa placa de 8GB o automatico decide paginar quase tudo; em 16/24GB+ ele passa a segurar os nichos na placa sozinho." },
  galeriaLoras:{ t:"LoRAs da biblioteca",
    b:"As 389 LoRAs do disco, com a miniatura e o DOMINIO lido de ss_tag_frequency — as etiquetas que o autor de fato mostrou ao modelo no treino, nao descricao escrita a mao. Clique numa miniatura para inserir as tags dela no prompt: o roteador le o prompt depois, convoca o centro correspondente, e a LoRA entra POR CIMA dele como carona em vez de virar mais um centro.",
    img:"Passe o mouse para ver o dominio antes de escolher. A etiqueta verde/laranja no canto diz o papel.",
    hw:"CARONA viaja dentro da passada de outro adaptador; CENTRO tem passada propria do UNet. Medido em 14/08 com 6 centros a 768: 89MB como centro +7,16 s/it, como carona +3,62 (-49%). Ja' 709MB nao economiza nada, porque a carona fica residente o tempo todo e come a folga que a passada economizava. Por isso o corte em 200MB.",
    hint:"O corte de 200MB e' palpite informado: medi 89MB e 709MB, o meio nao foi medido." },
  custo:{ t:"Custo previsto",
    b:"CAMADAS e' a linha que explica o tempo. Cada centro NAO e' uma LoRA empilhada no mesmo forward: ele assume o UNet inteiro por vez e produz a propria predicao sobre todo o latente; so' depois as predicoes se combinam por mascara. Entao N centros = N passadas completas por passo, mais duas (a sonda que extrai as mascaras e a base).",
    img:"Mais camadas = mais especialistas opinando na mesma imagem, cada um na sua regiao.",
    hw:"Medido em 13/08 decompondo o passo: paginar um centro custa ~0ms, trocar de adaptador 39ms, ceder contexto 40ms — as PASSADAS respondem por ~98% do tempo. O numero de camadas e' o custo, e nao a paginacao como se supunha antes. VRAM vem de medicao nesta maquina, nao de formula; os centros ficam paginados na RAM e sobem um por vez.",
    hint:"10 centros a 30 passos = 360 passadas contra 60 de um modelo comum. Para ir mais rapido, tire centros — nao passos." },
  hint:{ t:"Ajuda do canto", b:"Liga/desliga este balao. Desligado, passar o mouse pelos controles nao mostra mais nada — e a barra de progresso ocupa a largura toda.",
    img:"—", hw:"Sem custo.", hint:"O estado fica salvo p/ a proxima sessao." },
  steps:{ t:"Passos", b:"Quantas iteracoes de denoise. Mais passos refinam ate saturar.",
    img:"Mais nitidez/coerencia ate um teto (~26-30).", hw:"Tempo cresce linear com os passos." },
  cfg:{ t:"CFG", b:"O quanto a geracao obedece ao prompt vs. inventa livre.",
    img:"Alto gruda no prompt (pode queimar); baixo fica solto.", hw:"Sem custo extra." },
  seed:{ t:"Seed", b:"Semente do ruido inicial. Mesma seed + mesmos parametros = mesma imagem.",
    img:"Muda a composicao inteira.", hw:"Sem custo extra." },
  seedRand:{ t:"Seed aleatoria", b:"Sorteia uma seed nova a cada geracao.",
    img:"Cada clique = imagem diferente.", hw:"Sem custo." },

  hires:{ t:"Upscaler + Hires", b:"Amplia a imagem e roda um segundo denoise por cima, em camadas, para ganhar detalhe real (nao so esticar pixels).",
    img:"Mais resolucao e detalhe fino.", hw:"Cada camada = um roundtrip de VAE + passos extras. Pesa em tempo e VRAM.",
    hint:"O 'ganho' vai nos metadados (ex.: 1.5x)." },
  upscaler:{ t:"Upscaler", b:"Algoritmo que amplia antes do re-denoise (ex.: RealESRGAN anime).",
    img:"Define a base do detalhe ampliado.", hw:"RealESRGAN roda rapido na GPU." },
  hiresDenoise:{ t:"Denoise do hires", b:"Quanto a camada re-inventa sobre a imagem ampliada.",
    img:"Baixo preserva; alto redesenha (pode mudar a cena).", hw:"Sem custo extra alem dos passos." },

  ultra:{ t:"Ultra tiled (halo)", b:"Hires de alta resolucao em pedacos com sobreposicao, fundindo as bordas a cada passo (MultiDiffusion) para nao deixar costura — cabe em 8GB.",
    img:"Resolucao muito alta sem emenda visivel.", hw:"Pesado: N pedacos x passos. E a etapa mais lenta.",
    hint:"So a base pura refina os pedacos (sem wd14)." },
  ultraScale:{ t:"Escala do ultra", b:"Quanto ampliar no ultra. 1 = so detalhar, sem aumentar.",
    img:"Mais escala = mais pixels finais.", hw:"Cresce o numero de pedacos = mais tempo/VRAM." },
  ultraTile:{ t:"Tamanho do pedaco", b:"Lado de cada pedaco processado. Menor = mais pedacos, menos VRAM por vez.",
    img:"Nao muda o resultado, muda como e' fatiado.", hw:"Pedaco menor = mais passos, mais lento porem mais leve." },

  weighted:{ t:"Pesos no prompt", b:"Interpreta pesos estilo A1111 — (termo:1.3) reforca, [termo] enfraquece.",
    img:"Controle fino da enfase de cada termo.", hw:"Sem custo extra." },
  centerFocus:{ t:"Foco por centro", b:"Da mais peso ao termo-nucleo de cada centro e menos ao contexto, para o especialista nao se diluir.",
    img:"Identidade de cada centro mais nitida.", hw:"Sem custo extra." },
  preview:{ t:"Preview ao vivo (TAESD)", b:"Decodifica o latente a cada N passos com um autoencoder minusculo e mostra a imagem se formando.",
    img:"Nao altera o resultado — so mostra o progresso.", hw:"~2% por passo, ~2MB de VRAM. Barato.",
    hint:"O 1o decode faz um autotune unico (uma pausa curta)." },
  terminal:{ t:"Terminal do GSMDE", b:"Abre o log do worker numa janela a parte, com botao de copiar (tudo ou so o ultimo traceback). Fechar essa janela nao interrompe nada — a geracao continua.",
    img:"—", hw:"So le o arquivo de log.",
    hint:"'Copiar so o erro' pega do ultimo Traceback ate o fim." },
  centrosManual:{ t:"Centros (manual)", b:"Aparece com o automatico desligado. Marque o especialista para ativa-lo; as tags sao opcionais e so dizem ONDE ele age — sem tag marcada, o centro age na imagem toda.",
    img:"Voce decide quem pinta o que.", hw:"Cada centro marcado = ~0,7GB paginados por passo.",
    hint:"'preencher com o automatico' traz a escolha do roteador p/ voce so ajustar." },
  infinita:{ t:"Geracao infinita", b:"Encadeia rodadas ate voce clicar em parar. Cada rodada guarda a sua imagem (o nome carrega a seed), nada e' sobrescrito.",
    img:"Serve p/ garimpar seeds com os mesmos parametros.", hw:"O modelo fica carregado entre rodadas — so a geracao custa.",
    hint:"Exige seed aleatoria, senao repete a mesma imagem." },
  limpar:{ t:"Limpar intermediarias", b:"Apaga as imagens intermediarias da rodada anterior antes de gerar. A pasta 'final' NUNCA e' apagada.",
    img:"—", hw:"Sem custo.", hint:"Desligado = historico completo em outputs/gsmde/intermed." },
  reciclar:{ t:"Reciclar de uma imagem", b:"Abre um PNG e recarrega os parametros gravados nele: prompts, seed, centros, camadas, detailer e ultra. Imagem de fora traz so o basico (padrao A1111).",
    img:"Reproduz a imagem escolhida.", hw:"Instantaneo (so le o arquivo).",
    hint:"Desliga a seed aleatoria — reciclar e' p/ repetir, nao sortear." },
  camadas:{ t:"Camadas do hires", b:"Cada camada amplia por um GANHO sobre a largura base e roda um denoise por cima. Em cadeia: 1,5x com denoise medio -> 2,0x com denoise baixo e mais passos. O px resultante aparece na etiqueta da camada.",
    img:"Detalhe real ganho por etapa, sem reescrever a composicao.", hw:"Cada camada = 1 upscale + N passos. E' onde o tempo cresce.",
    hint:"Subir direto com denoise alto apaga os territorios dos centros." },
  detailer:{ t:"Detailer por alvo", b:"YOLO acha o alvo (rosto, maos, olhos...), recorta com folga, refaz o pedaco em img2img e cola com borda suave. Cada alvo tem PROMPT PROPRIO: o texto vale so naquele recorte.",
    img:"Corrige rosto/maos sem tocar no resto da cena.", hw:"Um denoise curto por deteccao — barato perto do hires.",
    hint:"Prompt vazio = usa o positivo da cena." },
  detMascarado:{ t:"Mascara com buracos", b:"Alvos vizinhos entram numa passada so, mas a mascara pinta UM BLOB POR ALVO em vez do retangulo que engloba todos. Com dois olhos, o nariz no meio fica de fora e nao e' redesenhado.",
    img:"So o alvo muda; o que esta entre os alvos fica intacto.", hw:"Nenhum custo extra — e' a mesma passada.",
    hint:"Desligar volta ao modo antigo, que refaz o recorte inteiro." },
  detPar:{ t:"Exigir par (olhos)", b:"Olho so' e' refeito junto com o outro. Se o detector achar um so, tenta achar o irmao com limiar baixo dentro do rosto; nao achando, pula o alvo.",
    img:"Impede o defeito de uma iris sair de cor diferente da outra.", hw:"Uma deteccao extra, barata.",
    hint:"Medido: repintar um olho sozinho deu um azul e um castanho." },
  detLadoMin:{ t:"Recorte minimo", b:"Piso do tamanho do recorte, em pixels da imagem original. Uma caixa de olho tem ~23px; sem piso ela seria ampliada 44x ate' a resolucao de geracao.",
    img:"Evita detalhe inventado em alvo minusculo.", hw:"Recorte maior = mais contexto, mesmo custo de passada." },
  detCrop:{ t:"Gerar em", b:"Resolucao em que o recorte e' refeito. Ele e' ampliado ate' aqui, refeito, e reduzido de volta na hora de costurar — assim o especialista trabalha perto da resolucao em que foi treinado.",
    img:"Maior = mais detalhe no alvo.", hw:"O custo da passada vem DAQUI, nao do tamanho do alvo: 1024 custa o mesmo para um olho e para um rosto." },
  ultraHalo:{ t:"Halo e sobreposicao", b:"O halo e' a borda de contexto que o modelo VE mas nao reescreve; a sobreposicao e' o quanto os pedacos escritos se cruzam antes do feather.",
    img:"Halo evita alucinacao na borda; sobreposicao esconde a costura.", hw:"Ambos aumentam a area processada por pedaco." },
  maskEvery:{ t:"Mascara a cada N passos", b:"De quantos em quantos passos as mascaras de territorio sao recalculadas.",
    img:"Menor = territorios mais firmes; maior = mais solto e rapido.", hw:"Recalcular custa um pouco de tempo por vez." },
  yield:{ t:"Yield anti-TDR", b:"Pausa curta entre operacoes na GPU para o Windows nao achar que a placa travou.",
    img:"Nao altera o resultado.", hw:"0 = mais rapido; acima de 0 evita o watchdog matar o processo." },
  i2i:{ t:"Imagem base (i2i)", b:"Parte de uma imagem sua em vez de ruido puro; o denoise a puxa para o prompt.",
    img:"Mantem a estrutura da imagem original.", hw:"Igual a uma geracao normal." },
  pose:{ t:"Controle de pose", b:"Usa um esqueleto OpenPose (ou extraido de uma referencia) para fixar a pose.",
    img:"Trava a pose/enquadramento do personagem.", hw:"ControlNet ativo = +VRAM (pode gerar spill/PCIe em 8GB)." },
};
